name: CI/CD Pipeline

on:
  push:
    tags:
      - pypi_[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy_package:
    runs-on: ubuntu-latest
    
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache
      PYPI_API: ${{ secrets.PYPI_API }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        sudo apt-get install make automake gcc g++ subversion python3-dev build-essential \
        freetype-dev libpng-dev libopenblas-dev libffi-dev
        python -V
        python -m pip install --upgrade pip
        python -m pip install -r requirements-build.txt

    - name: Configure PyPI credentials and deploy package
      run: |
        sed -i "s|^version =.*|version =${{ github.ref }}|" setup.cfg
        python -m build

        echo ${{ github.ref }}
        tag_name=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
        echo "Tag name: $tag_name"

    - name: Clean up
      run: |
        echo "" > ~/.pypirc && rm -f ~/.pypirc