name: CI/CD Pipeline

on:
  push:
    tags:
      - rscript_[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY_WEB: ${{ secrets.SSH_PRIVATE_KEY_WEB }}
      SSH_HOST_KEY_WEB: ${{ secrets.SSH_HOST_KEY_WEB }}
      SSH_USER_HOST_LOCATION_SCRIPT_WEB: ${{ secrets.SSH_USER_HOST_LOCATION_SCRIPT_WEB }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy documentation
      run: |
        sudo apt-get update && sudo apt-get install -y rsync
        which ssh-agent || (sudo apt-get update && sudo apt-get install -y openssh-client)
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        echo "${SSH_PRIVATE_KEY_WEB}" | ssh-add -
        echo "${SSH_HOST_KEY_WEB}" > ~/.ssh/known_hosts
        rsync -hrvz --delete scripts "${SSH_USER_HOST_LOCATION_SCRIPT_WEB}"